# Generated by Django 5.2.7 on 2025-12-03 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('common', '0003_alter_apisettings_created_by_and_more'),
        ('contacts', '0001_initial'),
        ('leads', '0001_initial'),
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_account',
            field=models.ForeignKey(blank=True, help_text='Account created from this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_leads', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, help_text='When the lead was converted', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_by',
            field=models.ForeignKey(blank=True, help_text='User who converted this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='common.profile'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_contact',
            field=models.ForeignKey(blank=True, help_text='Contact created from this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_leads', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_opportunity',
            field=models.ForeignKey(blank=True, help_text='Opportunity created from this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_leads', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_converted',
            field=models.BooleanField(default=False, help_text='Whether this lead has been converted'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('working', 'Working'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('on hold', 'On Hold'), ('converted', 'Converted')], max_length=255, null=True, verbose_name='Status of Lead'),
        ),
    ]
