# Generated by Django 5.2.8 on 2025-11-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='skype_ID',
        ),
        migrations.AddField(
            model_name='lead',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('less_5k', 'Less than €5,000'), ('5k_10k', '€5,000–€10,000'), ('10k_25k', '€10,000–€25,000'), ('over_25k', 'Over €25,000')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='decision_timeframe',
            field=models.CharField(blank=True, choices=[('1_week', 'Within 1 week'), ('1_month', 'Within 1 month'), ('3_months', 'Within 3 months'), ('more_3_months', 'More than 3 months')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='department',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Support', 'Support'), ('Finance', 'Finance'), ('Operations', 'Operations')], default='Sales', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='do_not_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_language',
            field=models.CharField(choices=[('English', 'English'), ('Dutch', 'Dutch'), ('Arabic', 'Arabic'), ('German', 'German'), ('French', 'French'), ('Spanish', 'Spanish')], default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='rating',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10, null=True),
        ),
    ]
