# Generated by Django 5.2.7 on 2025-11-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='do_not_call',
            field=models.CharField(blank=True, default='no', max_length=10, verbose_name='Do Not Call'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('event', 'Event'), ('email campaign', 'Email Campaign'), ('partner', 'Partner'), ('phone inquiry', 'Phone Inquiry'), ('other', 'Other')], max_length=255, null=True, verbose_name='Source of Lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('working', 'Working'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('on hold', 'On Hold')], max_length=255, null=True, verbose_name='Status of Lead'),
        ),
    ]
