# Generated by Django 5.2.8 on 2025-12-07 12:49

import django.db.models.deletion
from django.db import migrations, models, connection


def add_assigned_to_column(apps, schema_editor):
    """Add the assigned_to_id column with database-specific SQL."""
    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            # SQLite: Simple ADD COLUMN without constraint (char(32) for UUID storage)
            cursor.execute('ALTER TABLE "lead" ADD COLUMN "assigned_to_id" char(32) NULL;')
        else:
            # PostgreSQL: Use proper UUID type with FK constraint
            cursor.execute('''
                ALTER TABLE "lead" ADD COLUMN "assigned_to_id" uuid NULL 
                REFERENCES "profile" ("id") DEFERRABLE INITIALLY DEFERRED;
            ''')


def remove_assigned_to_column(apps, schema_editor):
    """Remove the assigned_to_id column."""
    with connection.cursor() as cursor:
        cursor.execute('ALTER TABLE "lead" DROP COLUMN "assigned_to_id";')


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_apisettings_created_by_and_more'),
        ('leads', '0002_add_lead_conversion_fields'),
    ]

    operations = [
        # Step 1: Remove the M2M field (this removes the intermediary table)
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        # Step 2: Use SeparateDatabaseAndState to add the FK field
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='lead',
                    name='assigned_to',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='lead_assigned_users',
                        to='common.profile',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_assigned_to_column, remove_assigned_to_column),
            ],
        ),
    ]
