# Generated by Django 5.2.7 on 2025-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('support', 'Support'), ('finance', 'Finance'), ('operations', 'Operations')], default='sales', max_length=50, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='lead',
            name='salutation',
            field=models.CharField(blank=True, choices=[('mr', 'Mr'), ('ms', 'Ms'), ('mrs', 'Mrs'), ('dr', 'Dr'), ('prof', 'Prof')], max_length=10, null=True, verbose_name='Salutation'),
        ),
    ]
