# Generated by Django 5.2.7 on 2025-11-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_department_lead_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('dutch', 'Dutch'), ('arabic', 'Arabic'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish')], db_column='preferred_language', default='english', max_length=50, verbose_name='Preferred Language'),
        ),
    ]
