# Generated by Django 5.2.7 on 2025-11-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='rating',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=10, verbose_name='Rating'),
        ),
    ]
