# Generated by Django 5.2.7 on 2025-11-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_add_lead_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('less_than_5000', 'Less than €5,000'), ('5000_to_10000', '€5,000–€10,000'), ('10000_to_25000', '€10,000–€25,000'), ('over_25000', 'Over €25,000')], max_length=50, null=True, verbose_name='Budget Range'),
        ),
    ]
