# Generated by Django 5.2.7 on 2025-11-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_add_lead_budget_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='decision_timeframe',
            field=models.CharField(blank=True, choices=[('within_1_week', 'Within 1 week'), ('within_1_month', 'Within 1 month'), ('within_3_months', 'Within 3 months'), ('more_than_3_months', 'More than 3 months')], max_length=50, null=True, verbose_name='Decision Timeframe'),
        ),
    ]
