# Generated by Django 5.2.7 on 2025-11-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_add_lead_decision_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='do_not_call',
            field=models.BooleanField(blank=True, default=False, verbose_name='Do Not Call'),
        ),
    ]
