# Generated by Django 5.2.7 on 2025-12-04 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_apisettings_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('user_role', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View')], max_length=20)),
                ('entity_type', models.CharField(choices=[('Lead', 'Lead'), ('Contact', 'Contact'), ('Account', 'Account'), ('Opportunity', 'Opportunity'), ('Case', 'Case'), ('User', 'User'), ('System', 'System')], max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='common.org')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', '-created_at'], name='activity_lo_org_id_29af46_idx'), models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_f9dfaa_idx'), models.Index(fields=['action'], name='activity_lo_action_f14761_idx'), models.Index(fields=['entity_type'], name='activity_lo_entity__30fbb7_idx')],
            },
        ),
    ]
