# Generated by Django 5.2.7 on 2025-12-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_view_others_activity_logs',
            field=models.BooleanField(default=False, help_text="Allow this user to view other users' activity logs. Users can always view their own logs."),
        ),
    ]
