# Generated by Django 5.2.8 on 2025-11-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
