# Generated by Django 5.2.7 on 2025-12-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('less_than_5000', 'Less than €5,000'), ('5000_to_10000', '€5,000–€10,000'), ('10000_to_25000', '€10,000–€25,000'), ('over_25000', 'Over €25,000')], max_length=50, null=True, verbose_name='Budget Range'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='decision_timeframe',
            field=models.CharField(blank=True, choices=[('within_1_week', 'Within 1 week'), ('within_1_month', 'Within 1 month'), ('within_3_months', 'Within 3 months'), ('more_than_3_months', 'More than 3 months')], max_length=50, null=True, verbose_name='Decision Timeframe'),
        ),
    ]
