# Generated by Django 5.2.7 on 2026-01-18 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_fix_deactivated_by_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report configuration name', max_length=255)),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('revenue', 'Revenue Report'), ('activity', 'Activity Report'), ('contact', 'Contact/Account Report'), ('case', 'Case/Support Report'), ('team', 'Team Performance Report')], max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('date_preset', models.CharField(blank=True, help_text="Preset like 'this_month', 'last_30_days', etc.", max_length=50, null=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Store filters like users, status, source, etc.')),
                ('metrics', models.JSONField(blank=True, default=list, help_text='List of metrics to include in the report')),
                ('grouping', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('user', 'By User'), ('team', 'By Team'), ('status', 'By Status'), ('source', 'By Source')], max_length=20, null=True)),
                ('include_graphics', models.BooleanField(default=True)),
                ('graphics_config', models.JSONField(blank=True, default=dict, help_text='Store chart types, colors, and other visual settings')),
                ('include_summary', models.BooleanField(default=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_tables', models.BooleanField(default=True)),
                ('include_logo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to='common.org')),
            ],
            options={
                'db_table': 'report_configuration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='common.org')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reportconfiguration')),
            ],
            options={
                'db_table': 'generated_report',
                'ordering': ['-generated_at'],
            },
        ),
    ]
